spring:
  application:
    name: spendlens-backend
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migrate: true

gemini:
  api:
    key: ${GEMINI_API_KEY}

resend:
  api:
    key: ${RESEND_API_KEY}

frontend:
  url: ${FRONTEND_URL}

rate-limit:
  capacity: 10
  refill-tokens: 10
  refill-duration-minutes: 60

logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    com.credex.spendlens: DEBUG
